//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YandexReports
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YandexFoodReportsEntities : DbContext
    {
        public static YandexFoodReportsEntities _context;
        public YandexFoodReportsEntities()
            : base("name=YandexFoodReportsEntities")
        {
        }
        public static YandexFoodReportsEntities GetContext
        {
            get
            {
                if (_context == null)
                    _context = new YandexFoodReportsEntities();
                return _context;
            }
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Day> Day { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
